/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package campmanager;

import javax.swing.JOptionPane;

/**
 *
 * @author Akshaya
 */
public class NewRoomPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewRoomPanel
     * 
     *  
     */
    
    Room room;
    boolean success;
    
    public NewRoomPanel() {
        initComponents();
        room=new Room();
        success=false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_room_no = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSpinner_room_capacity = new javax.swing.JSpinner();
        jTextField_bed_cost = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton_add_room = new javax.swing.JButton();

        jLabel1.setText("Room Number");

        jLabel2.setText("Capacity");

        jSpinner_room_capacity.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        jLabel3.setText("Bed Cost");

        jButton_add_room.setText("Add");
        jButton_add_room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_roomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_bed_cost, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(jTextField_room_no)
                    .addComponent(jSpinner_room_capacity))
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_add_room)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_room_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jSpinner_room_capacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_bed_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_add_room)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_add_roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add_roomActionPerformed
        // TODO add your handling code here:
        
        success=true;
        if(jTextField_room_no.getCaretPosition()==0){
            JOptionPane.showMessageDialog(null, "Enter Room Number", "Error", JOptionPane.ERROR_MESSAGE);
            success=false;
        }
            
        try{
            room.setCapacity(Integer.parseInt(jSpinner_room_capacity.getValue().toString()));

        }
        catch(Exception e){
            room.setCapacity(3);
            JOptionPane.showMessageDialog(null, "Invalid Input ! Room capacity set to 3", "Error", JOptionPane.ERROR_MESSAGE);
        }

        room.setRoom_no(jTextField_room_no.getText());
        try{
            room.setCost(Integer.parseInt(jTextField_bed_cost.getText()));
        }
        catch(Exception e){
            room.setCost(500);
            JOptionPane.showMessageDialog(null, "Invalid Input ! Room cost set to AED 500", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton_add_roomActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_add_room;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner jSpinner_room_capacity;
    private javax.swing.JTextField jTextField_bed_cost;
    private javax.swing.JTextField jTextField_room_no;
    // End of variables declaration//GEN-END:variables
}
