/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package campmanager;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;

/**
 *
 * @author Akshaya
 */
public class NewRoom extends javax.swing.JDialog {

    /**
     * Creates new form NewRoom
     */
    
     Room room;
     boolean success;
    public NewRoom(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        room =new Room();
        success=false;
         jTextField_bed_cost.setText("500");
         jSpinner_room_capacity.setValue(3);
    }
     public NewRoom(java.awt.Frame parent, boolean modal,Room room_here) {
        super(parent, modal);
        initComponents();
        room =new Room();
        success=false;
         setTitle("Edit Room");
        if(room_here!=null){
        jTextField_room_no.setText(room_here.getRoom_no().substring(0, room_here.getRoom_no().length()-1));
        jTextField_room_code.setText(room_here.getRoom_no().toString().substring(room_here.getRoom_no().length()-1));
        jTextField_room_cost.setText(Integer.toString(room_here.getRoom_cost()));
         jTextField_bed_cost.setText(Integer.toString(room_here.getCost()));
         jSpinner_room_capacity.setValue(room_here.getCapacity());
        }
    }

    public Room getRoom() {
        return room;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_room_no = new javax.swing.JTextField();
        jTextField_bed_cost = new javax.swing.JTextField();
        jButton_add_room = new javax.swing.JButton();
        jSpinner_room_capacity = new javax.swing.JSpinner();
        jLabel_code = new javax.swing.JLabel();
        jTextField_room_code = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_bld_no = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jTextField_room_cost = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox_no_code = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Room");

        jLabel1.setText("Room Number");

        jLabel2.setText("Capacity");

        jLabel3.setText("Bed Cost");

        jButton_add_room.setText("Add");
        jButton_add_room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_roomActionPerformed(evt);
            }
        });

        jSpinner_room_capacity.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        jLabel_code.setText("Code");

        jTextField_room_code.setText(" ");

        jLabel4.setText("AED");

        jLabel5.setText("Building");

        jComboBox_bld_no.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "J 3", "J 4", "J 6", "J 9", "J 10", "J 12", "JB 6", "JB 18", "L 4", "L 18", "L 25", "L 31", "S 17", "S 26", "SB 1" }));

        jLabel6.setText("Camp");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Junior Accommodation (New East )", "Senior Accommodation (New East)\t\t", "Labour Accommodaion (New East)\t\t", "Labour Accommodaion (South Camp)\t\t", "Junior Accommodation(South Camp)" }));

        jLabel7.setText("Room Cost p/a");

        jTextField_room_cost.setText(" ");
        jTextField_room_cost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_room_costActionPerformed(evt);
            }
        });

        jLabel8.setText("AED");

        jCheckBox_no_code.setText("No Code");
        jCheckBox_no_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_no_codeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_add_room, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(58, 58, 58)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox_bld_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField_room_cost, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_bed_cost, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                    .addComponent(jSpinner_room_capacity, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField_room_no, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_code)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_room_code, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox_no_code)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_room_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_code)
                    .addComponent(jTextField_room_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_no_code))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jSpinner_room_capacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_bed_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_room_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox_bld_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_add_room)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_add_roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add_roomActionPerformed
        // TODO add your handling code here:
        
        success=true;
       
        try{
         room.setCapacity(Integer.parseInt(jSpinner_room_capacity.getValue().toString()));
         
        }
        catch(Exception e){
            room.setCapacity(3);
            JOptionPane.showMessageDialog(null, "Invalid Input ! Room capacity set to 3", "Error", JOptionPane.ERROR_MESSAGE);
            success=false;
        }
        
        room.setRoom_no(jTextField_room_no.getText().trim()+" "+jTextField_room_code.getText().trim());
        try{
        room.setCost(Integer.parseInt(jTextField_bed_cost.getText()));
        room.setRoom_cost(Integer.parseInt(jTextField_room_cost.getText()));
        }
        catch(IllegalArgumentException e){
            room.setCost(500);
            JOptionPane.showMessageDialog(null, "Invalid Input ! ", "Error", JOptionPane.ERROR_MESSAGE);
            success=false;
        }
        
        room.setBld_no(jComboBox_bld_no.getSelectedItem().toString());
      
        room.setCamp(jComboBox1.getSelectedIndex());
       // System.out.println(jComboBox1.getSelectedIndex());
        if(success){
            final JPanel info=new JPanel();
            //JOptionPane.showMessageDialog(info, jTextField_room_no.getText()+" added .. ","Information",JOptionPane.INFORMATION_MESSAGE);
            dispose();
        }
    }//GEN-LAST:event_jButton_add_roomActionPerformed

    private void jTextField_room_costActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_room_costActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_room_costActionPerformed

    private void jCheckBox_no_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_no_codeActionPerformed
        // TODO add your handling code here:
        if(jCheckBox_no_code.isSelected()){
            jTextField_room_code.setText("-");
            jTextField_room_code.setEditable(false);
        }
        else{
            jTextField_room_code.setText("");
            jTextField_room_code.setEditable(true);
        }
    }//GEN-LAST:event_jCheckBox_no_codeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewRoom dialog = new NewRoom(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_add_room;
    private javax.swing.JCheckBox jCheckBox_no_code;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox_bld_no;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_code;
    private javax.swing.JSpinner jSpinner_room_capacity;
    private javax.swing.JTextField jTextField_bed_cost;
    private javax.swing.JTextField jTextField_room_code;
    private javax.swing.JTextField jTextField_room_cost;
    private javax.swing.JTextField jTextField_room_no;
    // End of variables declaration//GEN-END:variables
}
